// CONSTANTS NORMAL
export const GET_TASK_LIST_API = "GET_TASK_LIST_API";

// CONSTANT SAGA
export const GET_TASK_API_ACTION_SAGA = "GET_TASK_API_ACTION_SAGA";
export const ADD_TASK_API_ACTION_SAGA = "ADD_TASK_API_ACTION_SAGA";
export const DELETE_TASK_API_ACTION_SAGA = "DELETE_TASK_API_ACTION_SAGA";
export const CHECK_TASK_API_ACTION_SAGA = "CHECK_TASK_API_ACTION_SAGA";
export const REJECT_TASK_API_ACTION_SAGA = "REJECT_TASK_API_ACTION_SAGA";
